apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: softlight
    app.kubernetes.io/name: softlight
  name: softlight
  namespace: softlight
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: softlight
    app.kubernetes.io/name: softlight
  name: softlight
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:vmware-system-privileged
subjects:
- kind: ServiceAccount
  name: softlight
  namespace: softlight
